apiVersion: v1
kind: Service
metadata:
  name: nh-spring-boot
  namespace: default
  labels:
    app: nh-spring-boot
spec:
  selector:
    app: nh-spring-boot
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
